### ISSUE TITLE
in_account CPU ve LAG Problem

### ISSUE THREAD

**Issue by QueryOfficial** [inceptionnet/issues#1628]
![image](https://user-images.githubusercontent.com/76632145/212392195-f0b9c57e-860d-423d-ac54-fc1186635360.png)
![image](https://user-images.githubusercontent.com/76632145/212392354-c87299ad-5f42-4646-838a-49abe731ec25.png)
![image](https://user-images.githubusercontent.com/76632145/212392375-78b9bf3e-34c3-4692-8283-ad99c235a6c5.png)

**Comment by fresholia** [comment]
V4'de düzeltildi
